export const db = 'main-stackover'
export const questionCollection = 'questions'
export const answerCollection = 'answers'
export const commentCollection = 'comments'
export const voteCollections = 'votes'
export const questionAttachmentBucket = 'question-attachment'